### ISSUE TITLE
Error since last friday - Error retrieving plot data. See console for details.

### ISSUE THREAD

**Issue by ricds** [openforis/collect-earth-online#1656]
Hi devs, when i click at collect, the geodash shows the imagery and the plot correctly, but the page with the survey does not show and give this error: "Error retrieving plot data. See console for details."

In google chrome console, there is this error below:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at SimpleGeometry.setLayout (SimpleGeometry.js:195:34)
    at Polygon.setCoordinates (Polygon.js_+_1_modules:502:14)
    at new Polygon (Polygon.js_+_1_modules:292:19)
    at fromCircle (Polygon.js_+_1_modules:588:19)
    at mercator.asPolygonFeature (mercator.js_+_1_modules:1606:45)
    at Collection.eval [as createPlotKML] (collection.js_+_3_modules:1551:128)
    at Collection.componentDidUpdate (collection.js_+_3_modules:2005:16)
    at Ji (react-dom.production.min.js:212:231)
    at Sj (react-dom.production.min.js:255:229)
    at exports.unstable_runWithPriority (scheduler.production.min.js:19:467)
Ci @ react-dom.production.min.js:209
```

I have this error in multiple projects, new and old, this one for example has the error - https://app.collect.earth/collection?projectId=34974 - i also have projects that does not have the error, so i do not know what is going on.

**Comment by a-luz** [comment]
Hi Ricardo! I'm investigating what might be going wrong with the collection page. Can you send one more example of a project with this error?

Thank you!

**Comment by ricds** [comment]
Yes, these also has this issue:
https://app.collect.earth/collection?projectId=34629
https://app.collect.earth/review-project?projectId=34420

There are more if you need for trouble shooting. Thanks !

**Comment by a-luz** [comment]
Ok, we've managed to find and fix this issue. We'll be deploying this fix later today in the production server.

Thank you for the report

**Comment by ricds** [comment]
thanks, i confirm it is working
